### ISSUE TITLE
Cannot pass color props to Nav Component

### ISSUE THREAD

**Issue by CoveTechnologyAus** [johnleider/vue-materials#6]
I have noticed if I try to colour the Nav component it does not respect my colour style settings.
eg. 
```
<v-nav class="z-depth-1 blue-grey darken-4">
            <a href="#!" class="brand-logo" slot="logo">Logo</a>
            <ul class="right">
```

This will set the z-depth OK but does not set the color of the Nav.

Is there another way I should be setting the colors outside the way Material-css shows to do it?

**Comment by johnleider** [comment]
I'll take a look at this.

**Comment by Outpox** [comment]
@johnleider: I'm running in the same problem, have you had the time too look into it? :)

**Comment by johnleider** [comment]
No, I will get to this tonight.

**Comment by johnleider** [comment]
Materializecss wraps the navbar in a div, which is why the z-index was showing.  It is relatively positioned whereas the navbar is fixed, so the color is being applied to the outer div, but not the navbar.  Due to this structure, it made the most sense to add a specific prop for setting the navbar's class.

This will be nav-class="" and will be published later tonight.

**Comment by Outpox** [comment]
Good to me!
Thanks for your work :)
